version: '3.9'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - bubble

  otelcol:
    image: otel/opentelemetry-collector-contrib-dev:latest
    volumes:
      - ./otel-config.yml:/etc/otel/config.yaml
    ports:
      - "6832:6832/udp" # jaeger
    networks:
      - bubble

networks:
  bubble:
    external: true
