receivers:
  jaeger:
    protocols:
      thrift_binary:
      thrift_http:

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [ jaeger ]
      exporters: [ jaeger ]